src/Application.Web/Controllers/LoanController.cs
using Application.BLL;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Application.Web.Controllers
{
    public class LoanController : Controller
    {
        private readonly ILoanService _loanService;
        private readonly IUserService _userService;
        private readonly IPenaltyService _penaltyService;

        public LoanController(ILoanService loanService, IPenaltyService penaltyService, IUserService userService)
        {
            _loanService = loanService;
            _userService = userService;
            _penaltyService = penaltyService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles ="Member")]
        public async Task<IActionResult> ReturnLoan(Guid LoanId)
        {
            var result =await  _loanService.ReturnLoan(LoanId);
            if (result.Succeeded)
            {
                return RedirectToAction("Index",controllerName:"Home");
            }

            ModelState.AddModelError("",result.Errors.ToString());
            return RedirectToAction(actionName: "MyLoans", controllerName: "Member");
        }

        
    }
}

src/Application.Web/Controllers/MemberController.cs
using Application.BLL;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Application.Web.Controllers
{
    [Authorize(Roles = "Member" )]
    public class MemberController : Controller
    {

        private readonly IUserService _userService;
        private readonly ILoanService _loanService;
        private readonly IPenaltyService _penaltyService;

        public MemberController(IUserService userService, ILoanService loanService, IPenaltyService penaltyService)
        {
            _userService = userService;
            _loanService = loanService;
            _penaltyService = penaltyService;
        }

        /// <summary>
        ///  Admin Customized Dashboard
        /// </summary>
        /// <returns></returns>
        public IActionResult Dashboard()
        {
            return View();
        }

        // AlBooks with Search Feature , MyLoans, MyPenalties, MyLoans( returned) -> filter Query ( Where(l => l.IsReturned); 
        [HttpGet]
        [Authorize(Roles ="Member")]
        public async Task<IActionResult> MyLoans()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (string.IsNullOrEmpty(userId))
            {
                // Add error to ModelState for not being logged in
                ModelState.AddModelError("", "User is not logged in.");
                return RedirectToAction(controllerName: "Home", actionName: "Index");
            }

            Guid userID;
            // Try to parse the user ID to Guid
            if (!Guid.TryParse(userId, out userID))
            {
                // Add error to ModelState for invalid GUID format
                ModelState.AddModelError("", "Invalid user ID format.");
                return RedirectToAction(controllerName: "Home", actionName: "Index");

            }

            var loans = await _loanService.GetLoansByMember(userID);
            if (loans == null)
            {
                // Handle the case where GetLoansByMember returns null
                ModelState.AddModelError("", "No loans found for the user.");
                return RedirectToAction(controllerName: "Home", actionName: "Index");

            }

            loans = loans.Where(l => !l.IsReturned).ToList();

            ViewBag.UserName = User.Identity.Name;

            return View(loans);
        }

        [HttpGet]
        [Authorize(Roles ="Member")]
        public async Task<IActionResult> MyPenalties()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (string.IsNullOrEmpty(userId))
            {
                // Add error to ModelState for not being logged in
                ModelState.AddModelError("", "User is not logged in.");
                return RedirectToAction(controllerName: "Home", actionName: "Index");
            }

            Guid userID;
            // Try to parse the user ID to Guid
            if (!Guid.TryParse(userId, out userID))
            {
                // Add error to ModelState for invalid GUID format
                ModelState.AddModelError("", "Invalid user ID format.");
                return RedirectToAction(controllerName: "Home", actionName: "Index");

            }

            var penalties = await _penaltyService.GetPenaltiesByMember(userID);
            if (penalties == null)
            {
                // Handle the case where GetLoansByMember returns null
                ModelState.AddModelError("", "No loans found for the user.");
                return RedirectToAction(controllerName: "Home", actionName: "Index");

            }

            penalties = penalties.Where(l => !l.IsPaid).ToList();

            ViewBag.UserName = User.Identity.Name;

            return View(penalties);
        }

    }
}

src/Application.Web/Controllers/PenaltyController.cs
using Application.BLL;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Application.Web.Controllers
{
    public class PenaltyController : Controller
    {
        private readonly IPenaltyService _penaltyService;
        private readonly IUserService _userService;
        private readonly ILoanService _loanService;

        public PenaltyController(IPenaltyService penaltyService, ILoanService loanService, IUserService userService)
        {
            _penaltyService = penaltyService;
            _userService = userService;
            _loanService = loanService;
        }

        [HttpPost]
        [Authorize(Roles = "Member")]
        public async Task<IActionResult> Pay(Guid PenaltyId)
        {
            var penalty = await _penaltyService.GetPenaltyById(PenaltyId);

            if(penalty == null)
            {
                ModelState.AddModelError("", "Penalty Doesn't Exists");
                return RedirectToAction(controllerName: "Member", actionName: "MyPenalties");
            }
          
            var result =  await _penaltyService.PayPenalty(penalty.LoanId ?? Guid.NewGuid(), penalty.Amount ?? 0);

            if (!result.Succeeded)
                ModelState.AddModelError("", result.Errors.ToString());

            return RedirectToAction(controllerName: "Member", actionName: "MyPenalties");
        }
         
    }

}

src/Application.Web/Views/Member/Dashboard.cshtml
@{
    ViewData["Title"] = $"{ViewBag.UserName} Dashboard";
    Layout = "~/Views/Shared/_MemberLayout.cshtml";
}

<p>Welcome, @User?.Identity?.Name</p>

<!-- A set of Cards to manage entities in The System by admin-->

<div class="row">

    <!-- Books -->
    <div class="col-md-3">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Explore Books</h5>
                <p class="card-text">View books in the system.</p>
                <a href="@Url.Action("Index", "Book")" class="btn btn-primary"> Books</a>
            </div>
        </div>
    </div>

    <!-- Loans -->
    <div class="col-md-3">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Your Loans</h5>
                <p class="card-text">View books you've loaned.</p>
                <a href="@Url.Action("MyLoans", "Member")" class="btn btn-primary">My Loans</a>
            </div>
        </div>
    </div>

    <!-- Penalties -->
    <div class="col-md-3">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Your Penalties</h5>
                <p class="card-text">View and Oay penalties.</p>
                <a href="@Url.Action("MyPenalties", "Member")" class="btn btn-primary">My Penalties</a>
            </div>
        </div>
    </div>

</div>

src/Application.Web/Views/Member/MyLoans.cshtml
@model IEnumerable<Application.Shared.ReadLoanDto>


@{
     Layout = "~/Views/Shared/_MemberLayout.cshtml";
    ViewData["Title"] = $"{ViewBag.UserName} Loans";

}

@if (Model != null && Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>Book Title</th>
                <th>Loan Date</th>
                <th>Due Date</th>
                <th>Status</th>
                <th>Return</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var loan in Model)
            {
                <tr>
                    <td>@loan?.BookTitle</td>
                    <td>@loan?.LoanDate.ToShortDateString()</td>
                    <td>@loan?.DueDate.ToShortDateString()</td>
                    <td>
                        @if (loan.DueDate < DateTime.UtcNow)
                        {
                            <span class="text-danger">Late</span>
                        }
                        else
                        {
                            <span class="text-success">On Time</span>
                        }
                    </td>
                    <td>
                        <form asp-controller="Loan" asp-action="ReturnLoan" method="post" style="display:inline;">
                            <input type="hidden" name="LoanId" value="@loan.LoanId" />
                            <button type="submit" class="btn btn-Primary">Return</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>No loans available.</p>
}

src/Application.Web/Views/Member/MyPenalties.cshtml
@model IEnumerable<Application.Shared.ReadPenaltyDto> // Adjust the namespace accordingly
@{
    Layout = "~/Views/Shared/_MemberLayout.cshtml";
    ViewData["Title"] = $"{ViewBag.UserName} Penalties";
}
<h2>All Penalties</h2>

     @if (Model != null && Model.Any())
     {
        <table class="table">
            <thead>
                <tr>
                    <th>Amount</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>

                   @foreach (var penalty in Model)
                    {
                        <tr>
                            <td>@penalty.Amount.ToString()</td>
                            <td>
                                @if (penalty.IsPaid)
                                {
                                    <span class="text-success">Paid</span>
                                }
                                else
                                {
                                    <span class="text-danger">Not Paid</span>
                                }
                            </td>
                            <td>
                                <form asp-controller="Penalty" asp-action="Pay" method="post">
                                    <input type="hidden" name="PenaltyID" value="@penalty.PenaltyId"/>
                                    <button type="submit" class="btn btn-Success">Pay</button>
                                </form>
                            </td>
                        </tr>
                    }
            </tbody>
        </table>
    }
    else
    {
        <tr>
            <td colspan="5">No penalties found.</td>
        </tr>
    }
<div>
    <a asp-action="Dashboard" class="btn btn-primary">Back to Dashboard</a> <!-- Adjust link as needed -->
</div>